### ISSUE TITLE
Fails to build on several architectures

### ISSUE THREAD

**Issue by CDLuminate** [google/highwayhash#66]
The newest version (Jan 3 2018) of highwayhash fails to build on several architecutures, as shown in the following link: https://buildd.debian.org/status/package.php?p=highwayhash&suite=experimental

Succeed: amd64, arm64, x32

Failed: armel, armhf, i386, mips, mips64el, ppc64el, s390x, alpha, hppa, hurd-i386, ia64, powerpc, ppc64, sh4, sparc64

Not sure: kfreebsd-amd64, kfreebsd-i386

I'd like to confirm whether your supported architectures are amd64 and arm64. If so, I'll set the package no longer to build on other architectures. Thanks

**Comment by jan-wassenberg** [comment]
Thank you for reporting this.
We also support ppc64 using Bazel. Looks like the Makefile needs updating.
Inserting the following should fix the [build error](https://buildd.debian.org/status/fetch.php?pkg=highwayhash&arch=ppc64&ver=0~20180103-geeea446-1&stamp=1516433197&raw=0
):

```ifdef HH_POWER
HH_X64 =
HIGHWAYHASH_OBJS += obj/hh_vsx.o
HIGHWAYHASH_TEST_OBJS += obj/highwayhash_test_vsx.o
VECTOR_TEST_OBJS += obj/vector_test_vsx.o
else
```
I'll push this change soon.

Yes, please help to disable builds on `*arm*,*i386,mips*,s390x,alpha,hppa,ia64,powerpc,sh4,sparc64`.

**Comment by jan-wassenberg** [comment]
Updated Makefile and added source file: d2dc080d540ac838c9b8f21d20879070699c50b6

**Comment by CDLuminate** [comment]
I'm updating the package.

**Comment by CDLuminate** [comment]
Oops. Still failing on ppc64, see https://buildd.debian.org/status/package.php?p=highwayhash&suite=experimental

ppc64el https://buildd.debian.org/status/fetch.php?pkg=highwayhash&arch=ppc64el&ver=0%7E20180103-geeea446-2&stamp=1518050846&raw=0

ppc64 https://buildd.debian.org/status/fetch.php?pkg=highwayhash&arch=ppc64&ver=0%7E20180103-geeea446-2&stamp=1518052138&raw=0

**Comment by CDLuminate** [comment]
I just cherry-picked the ppc64 fix to that package. 8325e91ad54922206f86dde03351118a1318424f is not included.

**Comment by jan-wassenberg** [comment]
Thanks for trying, my attempt at remote diagnosis failed ;)
I just installed a cross-compiler and fixed the Makefile plus two ifdef.
Hopefully will push the change tomorrow.

**Comment by jan-wassenberg** [comment]
Done, 14dedec and c5e6e544edb6523f11111bb7c0ab09011416760f.
I tested with powerpc64le-linux-gnu-g++ and `make all HH_POWER=1`. Please let me know whether all issues are resolved :)

**Comment by CDLuminate** [comment]
I'll upload a new version later with the new commits.

**Comment by CDLuminate** [comment]
ppc64el and arm64 builds were successful.

https://buildd.debian.org/status/package.php?p=highwayhash&suite=experimental

(the failures were due to packaging problems)

However ppc build is failing

**Comment by jan-wassenberg** [comment]
Thank you for letting me know :)
Looks like the POWER8 instructions we require are not available on ppc. In that case, how about we  disable ppc and keep only ppc64el as supported?

**Comment by CDLuminate** [comment]
@jan-wassenberg No problem. I plan to upload the package to unstable next time. Once uploaded, ubuntu bot will automatically pull that package to ubuntu devel soon.

**Comment by jan-wassenberg** [comment]
Sounds good :D Please let me know if you need any further input.

**Comment by CDLuminate** [comment]
@jan-wassenberg https://buildd.debian.org/status/package.php?p=highwayhash

The build failures are all resolved. I'm marking this issue as done.

**Comment by jan-wassenberg** [comment]
Thank you :)
